Repository nickytonline/connect-four, pull requests merged in 2022-10, with the labels that each got.

#10 chore: updated contributing guide
  CONTRIBUTING.md
Labels: documentation

#5 chore: add Gitpod support
  .gitpod.yml
  .lintstagedrc.cjs
  README.md
  gitpod-loading.png
  gitpod.png
  open-in-gitpod-container-vscode.png
  svelte-for-vs-code-extension.png
Labels: dx

#29 chore: Loosened Node 16 version for node engine
  package.json
Labels: dx

#32 Feature/add favicon
  static/favicon.png
Labels: design

#72 feat: added storybook
  .eslintrc.cjs
  .npmrc
  .storybook/main.cjs
  .storybook/preview-head.html
  .storybook/preview.cjs
  package-lock.json
  package.json
  src/stories/Button.stories.js
  src/stories/Button.svelte
  src/stories/Header.stories.js
  src/stories/Header.svelte
  src/stories/Introduction.stories.mdx
  src/stories/Page.stories.js
  src/stories/Page.svelte
  src/stories/assets/code-brackets.svg
  src/stories/assets/colors.svg
  src/stories/assets/comments.svg
  src/stories/assets/direction.svg
  src/stories/assets/flow.svg
  src/stories/assets/plugin.svg
  src/stories/assets/repo.svg
  src/stories/assets/stackalt.svg
  src/stories/button.css
  src/stories/header.css
  src/stories/page.css
Labels: dx
